#! /bin/bash

set -e

# Run JSDefer in a default configuration
dirs=$(find . -type d)
sqlite3 all.db <logging.sql
$0.native -b all.db $use_det $dirs
(echo "Page,Script #,Load,Address,Verdict,DOM writes, Assumed det?,Nondeterminism,URL";
 cat */*.csv) >all.csv
        

